from typing import List
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models.ai_negotiation import AINegotiation
from app.repositories.base import BaseRepository

class AINegotiationRepository(BaseRepository[AINegotiation]):
    """AINegotiationRepository managing SQL operations for AINegotiation drafts."""
    
    def __init__(self):
        super().__init__(AINegotiation)

    async def get_by_loan_id(self, db: AsyncSession, loan_id: int) -> List[AINegotiation]:
        """Fetch all negotiation letters drafted for a specific loan ID."""
        query = select(self.model).where(self.model.loan_id == loan_id)
        result = await db.execute(query)
        return list(result.scalars().all())

    async def get_by_user_id(self, db: AsyncSession, user_id: int) -> List[AINegotiation]:
        """Fetch all negotiation drafts generated by a specific user."""
        from app.models.loan import Loan
        query = select(self.model).join(Loan).where(Loan.user_id == user_id)
        result = await db.execute(query)
        return list(result.scalars().all())

# Global instance for easy import and reuse
ai_negotiation_repository = AINegotiationRepository()
