from datetime import datetime
from sqlalchemy import ForeignKey, Text, DateTime, func
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.models.base import Base

class AIHistory(Base):
    """Auditable log of user actions, query prompts, and AI outputs generated by the platform."""
    __tablename__ = "ai_histories"

    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), 
        nullable=False, 
        index=True
    )
    
    query: Mapped[str] = mapped_column(Text, nullable=False)
    response: Mapped[str] = mapped_column(Text, nullable=False)
    
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), 
        server_default=func.now(), 
        nullable=False,
        index=True
    )

    # Relationships
    user: Mapped["User"] = relationship(back_populates="ai_histories")

    def __repr__(self) -> str:
        return f"<AIHistory(id={self.id}, user_id={self.user_id}, timestamp={self.timestamp})>"
