import logging
from typing import List, Optional
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.ai_history import AIHistory
from app.schemas.ai_history import AIHistoryCreate
from app.repositories.ai_history import AIHistoryRepository, ai_history_repository

logger = logging.getLogger("app.services.ai_history")

class AIHistoryService:
    """Manages business operations coordinates for fetching AI query audit history trails."""
    
    def __init__(self, repo: AIHistoryRepository = ai_history_repository):
        self.repo = repo

    async def get_history_by_user(self, db: AsyncSession, user_id: int, skip: int = 0, limit: int = 100) -> List[AIHistory]:
        """Fetch audit log items generated by a user, sorted chronologically."""
        return await self.repo.get_by_user_id(db, user_id, skip=skip, limit=limit)

    async def log_history_item(self, db: AsyncSession, user_id: int, history_in: AIHistoryCreate) -> AIHistory:
        """Manually creates a new audit trail item."""
        db_history = AIHistory(
            user_id=user_id,
            query=history_in.query,
            response=history_in.response
        )
        created_history = await self.repo.create(db, db_history)
        logger.info(f"AI history record ID {created_history.id} created manually for user ID: {user_id}")
        return created_history

    async def clear_user_history(self, db: AsyncSession, user_id: int) -> bool:
        """Clear all audit history logs for the given user."""
        logger.info(f"Clearing all AI history logs for user ID: {user_id}")
        return await self.repo.delete_all_by_user_id(db, user_id)

    async def delete_history_item(self, db: AsyncSession, history_id: int, user_id: int) -> bool:
        """Delete a single AI history item if it belongs to the user."""
        item = await self.repo.get_by_id(db, history_id)
        if not item or item.user_id != user_id:
            logger.warning(f"Delete history item failed: Item {history_id} not found or unauthorized for User {user_id}")
            return False
        logger.info(f"Deleting AI history record ID {history_id} for user ID {user_id}")
        return await self.repo.delete(db, item)

# Global singleton instance
ai_history_service = AIHistoryService()
