from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict

class AIHistoryBase(BaseModel):
    """Shared base properties for AIHistory validations."""
    query: str = Field(..., description="The query prompt sent to the AI system")
    response: str = Field(..., description="The response output generated by the AI system")

class AIHistoryCreate(AIHistoryBase):
    """Schema for validating history creation inputs."""
    user_id: int = Field(..., description="ID of the user who triggered the request")

class AIHistoryUpdate(BaseModel):
    """Schema for updating history details. All fields are optional."""
    query: Optional[str] = None
    response: Optional[str] = None

class AIHistoryResponse(AIHistoryBase):
    """Schema for serializing audit logs in API responses."""
    id: int
    user_id: int
    timestamp: datetime

    model_config = ConfigDict(from_attributes=True)
